services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  lindesbs\toolbox\:
    resource: ../../*
    exclude: ../../{Entity,Entity,Migrations,Resources,Tests}

  lindesbs\toolbox\Command\:
    resource: '../../Command/*'

